### ISSUE TITLE
--no_upload parameter not working

### ISSUE THREAD

**Issue by bedroesb** [usegalaxy-eu/ena-upload-cli#33]
when running the example command following error is thrown:

```
ena-upload-cli --action add --center 'VIB-UGENT' --study example_tables/ENA_template_studies.tsv --sample example_tables/ENA_template_samples.tsv --experiment example_tables/ENA_template_experiments.tsv --run example_tables/ENA_template_runs.tsv --data example_data/*gz --dev --secret .secret.yml --no_upload
No files will be uploaded, remove `--no_upload' argument to perform upload.
No valid checksums found, generate now... Traceback (most recent call last):
  File "/home/bedro/.local/bin/ena-upload-cli", line 8, in <module>
    sys.exit(main())
  File "/home/bedro/.local/lib/python3.8/site-packages/ena_upload/ena_upload.py", line 733, in main
    md5 = df['file_name'].apply(lambda x: file_md5[x]).values
  File "/home/bedro/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4138, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2467, in pandas._libs.lib.map_infer
  File "/home/bedro/.local/lib/python3.8/site-packages/ena_upload/ena_upload.py", line 733, in <lambda>
    md5 = df['file_name'].apply(lambda x: file_md5[x]).values
KeyError: 'ENA_TEST2.R1.fastq.gz'

```

**Comment by bedroesb** [comment]
update, this is working, but md5 checksum need to be given in the table. This was not documented.
