### ISSUE TITLE
nan is filled in when column is mandatory and cell is empty

### ISSUE THREAD

**Issue by bedroesb** [usegalaxy-eu/ena-upload-cli#62]
This tricks the validation although nothing is present

**Comment by bedroesb** [comment]
This does give an error when the column has a controlled vocabulairy:

```
Traceback (most recent call last):
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/eval.py", line 301, in lookup_attr
    val = getattr(obj, key)
AttributeError: 'float' object has no attribute 'lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/eval.py", line 307, in lookup_attr
    val = obj[key]
TypeError: 'float' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/bin/ena-upload-cli", line 10, in <module>
    sys.exit(main())
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/ena_upload/ena_upload.py", line 953, in main
    schema_xmls = run_construct(
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/ena_upload/ena_upload.py", line 298, in run_construct
    schema_xmls[schema] = construct_xml(schema, stream, xsds[schema])
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/ena_upload/ena_upload.py", line 235, in construct_xml
    xml_string = stream.render(method='xml', encoding='utf-8')
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/core.py", line 184, in render
    return encode(generator, method=method, encoding=encoding, out=out)
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/output.py", line 59, in encode
    return _encode(''.join(list(iterator)))
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/output.py", line 243, in __call__
    for kind, data, pos in stream:
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/output.py", line 674, in __call__
    for kind, data, pos in stream:
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/output.py", line 779, in __call__
    for kind, data, pos in chain(stream, [(None, None, None)]):
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/output.py", line 598, in __call__
    for ev in stream:
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/core.py", line 292, in _ensure
    for event in stream:
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/base.py", line 641, in _include
    for event in stream:
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/markup.py", line 326, in _match
    for event in stream:
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/base.py", line 621, in _flatten
    stream = _apply_directives(data[1], data[0], ctxt, vars)
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/base.py", line 275, in _apply_directives
    stream = directives[0](iter(stream), directives[1:], ctxt, **vars)
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/directives.py", line 648, in __call__
    matched = bool(_eval_expr(self.expr, ctxt, vars))
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/base.py", line 290, in _eval_expr
    retval = expr.evaluate(ctxt)
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/eval.py", line 160, in evaluate
    return eval(self.code, _globals, {'__data__': data})
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/ena_upload/templates/ENA_template_PLATFORM.xml", line 12, in <Expression "row.instrument_model.lower().strip() == 'hiseq x five'">
    <INSTRUMENT_MODEL py:when="row.instrument_model.lower().strip() == 'hiseq x five'">HiSeq X Five</INSTRUMENT_MODEL>
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/eval.py", line 309, in lookup_attr
    val = cls.undefined(key, owner=obj)
  File "/gpfs/space/galaxy/service/dependencies/_conda/envs/__ena-upload-cli@0.6.0/lib/python3.10/site-packages/genshi/template/eval.py", line 397, in undefined
    raise UndefinedError(key, owner=owner)
genshi.template.eval.UndefinedError: nan has no member named "lower"
cp: cannot stat './ENA_template_experiment_updated.tsv': No such file or directory
cp: cannot stat './ENA_template_sample_updated.tsv': No such file or directory
cp: cannot stat './ENA_template_study_updated.tsv': No such file or directory
cp: cannot stat './ENA_template_run_updated.tsv': No such file or directory
```

This needs to be logged better
